### ISSUE TITLE
Auto utag.view

### ISSUE THREAD

**Issue by tapsboy** [moroshko/gatsby-plugin-tealium-utag#1]
Thanks for this plugin.

Shouldn't this plugin also take care of utag.view calls during page route changes. Something like: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js?

**Comment by moroshko** [comment]
As its name suggests, the purpose of this plugin is to simply inject the `utag`.
Check out [other related projects](https://github.com/moroshko/gatsby-plugin-tealium-utag#related) for automating tracking.
